# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate

default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
    - id: black-jupyter

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (python)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.4
    hooks:
    - id: commitizen
      stages: [commit-msg]
    - id: commitizen-branch
      stages: [pre-push]
